### ISSUE TITLE
Side effects in reducers

### ISSUE THREAD

**Issue by anupvarghese** [neolivz/redux-async-action-reducer#1]
One of the key [principles](http://redux.js.org/docs/introduction/ThreePrinciples.html) of redux application is predictability of the application at any point in time.

Use of [side-effects](https://github.com/neolivz/redux-async-action-reducer/blob/master/lib/reducers/async-reducer.ts#L61) should not be in reducer.

**Comment by neolivz** [comment]
Are you talking about creating Date? I guess I should remove that.

**Comment by anupvarghese** [comment]
@neolivz Yes. Also, I am not sure about the async reducers. Reducer has to be synchronous IMO.

**Comment by neolivz** [comment]
Reducer is synchronous. The action will call api and call reducer depends
on success or failure.
